### ISSUE TITLE
"How cmd.exe extracts a command": safest method is wrong

### ISSUE THREAD

**Issue by AndreyMZ** [johnstevenson/winbox-args#1]
### Problem description

https://github.com/johnstevenson/winbox-args/wiki/How-cmd.exe-extracts-a-command
> The safest method is to always force the use of the second rule by enclosing the command in double-quotes

In general enclosing the command in double-quotes does not force the use of the second rule.

### Steps to reproduce

```
C:\temp\test>ls -1
program.bat
program.bat foo.bat

C:\temp\test>cmd.exe /C "program.bat foo"
"program.bat foo.bat" is executed.
```

### Possible solution

`\S` switch forces the use of the second rule:

```
C:\temp\test>ls -1
program.bat
program.bat foo.bat

C:\temp\test>cmd.exe /S /C "program.bat foo"
"program.bat" is executed.
```

**Comment by johnstevenson** [comment]
Hmm.

> In general enclosing the command in double-quotes does not force the use of the second rule.

Sorry, but in general it does. Of course it won't if you want to run `program.bat` with the `foo` argument and you have another program named exactly `program.bat foo.bat` in the cwd or on the Path. But how likely is that?

It is an entertaining example (thanks) but you have taken it out of context. Perhaps I need to reword stuff slightly, but this repo is about providing better argument-escaping for PHP on Windows: as such there is no easy way to pass the `/S` option to cmd.exe.
